#include <ButtonConstants.au3>
#include <EditConstants.au3>
#include <GUIConstantsEx.au3>
#include <GUIListBox.au3>
#include <StaticConstants.au3>
#include <WindowsConstants.au3>
Opt("GUIResizeMode", $GUI_DOCKBOTTOM)
#Region ### START Koda GUI section ### Form=C:\Users\blundeen\AppData\Local\Apps\repos\find_files\Searchpt.kxf
$Form1 = GUICreate("Search For a Report", 556, 677, -1, -1, BitOR($GUI_SS_DEFAULT_GUI,$WS_SIZEBOX,$WS_THICKFRAME))
GUISetIcon("C:\Windows\System32\shell32.dll", -23)
GUISetFont(8, 400, 0, "Candara")
GUISetBkColor(0xFFFFFF)
$path_group = GUICtrlCreateGroup("Type a search path below or use the location button", 8, 8, 538, 105)
GUICtrlSetFont(-1, 12, 400, 0, "Candara")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKRIGHT+$GUI_DOCKTOP+$GUI_DOCKHEIGHT)
$path_input = GUICtrlCreateInput("", 16, 36, 521, 27)
GUICtrlSetFont(-1, 12, 400, 0, "Consolas")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKRIGHT+$GUI_DOCKTOP+$GUI_DOCKHEIGHT)
$path_btn = GUICtrlCreateButton("Location", 16, 72, 100, 25, BitOR($BS_DEFPUSHBUTTON,$BS_VCENTER,$BS_FLAT))
GUICtrlSetFont(-1, 14, 400, 0, "Candara")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKTOP+$GUI_DOCKWIDTH+$GUI_DOCKHEIGHT)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$search_group = GUICtrlCreateGroup("Type the patient's first and last name below in lowercase", 6, 118, 537, 185, BitOR($GUI_SS_DEFAULT_GROUP,$BS_FLAT,$WS_CLIPSIBLINGS))
GUICtrlSetFont(-1, 12, 400, 0, "Candara")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKRIGHT+$GUI_DOCKTOP+$GUI_DOCKHEIGHT)
$lastname_input = GUICtrlCreateInput("", 14, 166, 521, 27)
GUICtrlSetFont(-1, 12, 400, 0, "Consolas")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKRIGHT+$GUI_DOCKTOP+$GUI_DOCKHEIGHT)
$firstname_input = GUICtrlCreateInput("", 14, 227, 521, 27)
GUICtrlSetFont(-1, 12, 400, 0, "Consolas")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKRIGHT+$GUI_DOCKTOP+$GUI_DOCKHEIGHT)
$search_btn = GUICtrlCreateButton("Search", 16, 264, 100, 25, BitOR($BS_DEFPUSHBUTTON,$BS_VCENTER,$BS_FLAT))
GUICtrlSetFont(-1, 14, 400, 0, "Candara")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKTOP+$GUI_DOCKWIDTH+$GUI_DOCKHEIGHT)
$lastname_lbl = GUICtrlCreateLabel("Lastname:", 16, 144, 87, 27)
GUICtrlSetFont(-1, 14, 400, 0, "Candara")
GUICtrlSetResizing(-1, $GUI_DOCKAUTO+$GUI_DOCKLEFT+$GUI_DOCKTOP+$GUI_DOCKWIDTH+$GUI_DOCKHEIGHT)
$firstname_lbl = GUICtrlCreateLabel("Firstname:", 16, 203, 89, 27)
GUICtrlSetFont(-1, 14, 400, 0, "Candara")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKTOP+$GUI_DOCKWIDTH+$GUI_DOCKHEIGHT)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$List1 = GUICtrlCreateList("", 8, 344, 537, 289, BitOR($LBS_NOTIFY,$LBS_SORT,$WS_HSCROLL,$WS_VSCROLL))
GUICtrlSetFont(-1, 12, 400, 0, "Consolas")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKRIGHT+$GUI_DOCKTOP+$GUI_DOCKBOTTOM+$GUI_DOCKHEIGHT)
$results_lbl = GUICtrlCreateLabel("Search results will appear below", 8, 316, 222, 23)
GUICtrlSetFont(-1, 12, 400, 0, "Candara")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKTOP+$GUI_DOCKWIDTH+$GUI_DOCKHEIGHT)
$copy_btn = GUICtrlCreateButton("Copy", 384, 641, 75, 25, BitOR($BS_DEFPUSHBUTTON,$BS_VCENTER,$BS_FLAT))
GUICtrlSetFont(-1, 12, 400, 0, "Candara")
GUICtrlSetResizing(-1, $GUI_DOCKRIGHT+$GUI_DOCKBOTTOM+$GUI_DOCKWIDTH+$GUI_DOCKHEIGHT)
$copy_lbl = GUICtrlCreateLabel("Copy the files to a new location", 168, 644, 213, 23)
GUICtrlSetFont(-1, 12, 400, 0, "Candara")
GUICtrlSetResizing(-1, $GUI_DOCKRIGHT+$GUI_DOCKBOTTOM+$GUI_DOCKWIDTH+$GUI_DOCKHEIGHT)
$clear_btn = GUICtrlCreateButton("Clear", 469, 641, 75, 25, BitOR($BS_DEFPUSHBUTTON,$BS_CENTER,$BS_VCENTER))
GUICtrlSetFont(-1, 12, 400, 0, "Candara")
GUICtrlSetResizing(-1, $GUI_DOCKRIGHT+$GUI_DOCKBOTTOM+$GUI_DOCKWIDTH+$GUI_DOCKHEIGHT)
GUISetState(@SW_SHOW)
#EndRegion ### END Koda GUI section ###
