#include <ButtonConstants.au3>
#include <EditConstants.au3>
#include <GUIConstantsEx.au3>
#include <GUIListBox.au3>
#include <StaticConstants.au3>
#include <WindowsConstants.au3>
Opt("GUIResizeMode", $GUI_DOCKBOTTOM)
#Region ### START Koda GUI section ### Form=C:\Users\lunde\repos\NSH\find_files\Searchpt.kxf
$Form1 = GUICreate("Search For a Report", 556, 657, -1, -1, BitOR($GUI_SS_DEFAULT_GUI,$WS_SIZEBOX,$WS_THICKFRAME))
GUISetIcon("C:\Windows\System32\shell32.dll", -23)
$path_group = GUICtrlCreateGroup("Type a search path below or use the location button", 8, 8, 538, 97)
GUICtrlSetFont(-1, 10, 400, 0, "Lucida Fax")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKRIGHT+$GUI_DOCKTOP+$GUI_DOCKHEIGHT)
$path_input = GUICtrlCreateInput("", 16, 36, 521, 27)
GUICtrlSetFont(-1, 12, 400, 0, "Consolas")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKRIGHT+$GUI_DOCKTOP+$GUI_DOCKHEIGHT)
$path_btn = GUICtrlCreateButton("Location", 16, 72, 75, 25)
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKTOP+$GUI_DOCKWIDTH+$GUI_DOCKHEIGHT)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$search_group = GUICtrlCreateGroup("Type the patient's first and last name below in lowercase", 6, 110, 537, 177, BitOR($GUI_SS_DEFAULT_GROUP,$BS_FLAT,$WS_CLIPSIBLINGS))
GUICtrlSetFont(-1, 10, 400, 0, "Lucida Fax")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKRIGHT+$GUI_DOCKTOP+$GUI_DOCKHEIGHT)
$lastname_input = GUICtrlCreateInput("", 14, 158, 521, 27)
GUICtrlSetFont(-1, 12, 400, 0, "Consolas")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKRIGHT+$GUI_DOCKTOP+$GUI_DOCKHEIGHT)
$firstname_input = GUICtrlCreateInput("", 14, 219, 521, 27)
GUICtrlSetFont(-1, 12, 400, 0, "Consolas")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKRIGHT+$GUI_DOCKTOP+$GUI_DOCKHEIGHT)
$search_btn = GUICtrlCreateButton("Search", 16, 256, 75, 25)
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKTOP+$GUI_DOCKWIDTH+$GUI_DOCKHEIGHT)
$lastname_lbl = GUICtrlCreateLabel("Lastname:", 16, 136, 70, 20)
GUICtrlSetResizing(-1, $GUI_DOCKAUTO+$GUI_DOCKLEFT+$GUI_DOCKTOP+$GUI_DOCKWIDTH+$GUI_DOCKHEIGHT)
$firstname_lbl = GUICtrlCreateLabel("Firstname:", 16, 195, 73, 20)
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKTOP+$GUI_DOCKWIDTH+$GUI_DOCKHEIGHT)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$List1 = GUICtrlCreateList("", 8, 328, 537, 289, BitOR($LBS_NOTIFY,$LBS_SORT,$WS_HSCROLL,$WS_VSCROLL))
GUICtrlSetFont(-1, 12, 400, 0, "Consolas")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKRIGHT+$GUI_DOCKTOP+$GUI_DOCKBOTTOM+$GUI_DOCKHEIGHT)
$results_lbl = GUICtrlCreateLabel("Search results will appear below", 8, 300, 210, 20)
GUICtrlSetFont(-1, 10, 400, 0, "Lucida Fax")
GUICtrlSetResizing(-1, $GUI_DOCKLEFT+$GUI_DOCKTOP+$GUI_DOCKWIDTH+$GUI_DOCKHEIGHT)
$copy_btn = GUICtrlCreateButton("Copy", 448, 624, 75, 25)
GUICtrlSetResizing(-1, $GUI_DOCKRIGHT+$GUI_DOCKBOTTOM+$GUI_DOCKWIDTH+$GUI_DOCKHEIGHT)
$copy_lbl = GUICtrlCreateLabel("Copy the files to a new location", 240, 628, 207, 20)
GUICtrlSetFont(-1, 10, 400, 0, "Lucida Fax")
GUICtrlSetResizing(-1, $GUI_DOCKRIGHT+$GUI_DOCKBOTTOM+$GUI_DOCKWIDTH+$GUI_DOCKHEIGHT)
GUISetState(@SW_SHOW)
#EndRegion ### END Koda GUI section ###
